// src/vue/GanttEditorComponent.vue
<template>
  <div
    :ref="setChartContainerRef"
    class="chart-container"
    @mousemove="onContainerMouseMove"
    @mouseenter="onMouseEnter"
    @mouseleave="onMouseLeave"
  >

    <div
      v-if="$slots['top-content'] || topContentPortion"
      class="top-content-container"
      :style="{ height: currentTopContentHeight + 'px' }"
    >
      <slot name="top-content"></slot>
    </div>

    <div class="chart-canvas-wrap">
      <canvas
        :ref="setChartCanvasRef"
        class="chart-canvas"
        @mousedown="onCanvasMouseDown"
        @pointerup="onCanvasPointerUp"
        @click="onCanvasClick"
        @dblclick="onCanvasDoubleClick"
        @contextmenu.prevent
        @mousemove="onChartMouseMove"
        @mouseleave="onChartMouseLeave"
      ></canvas>
    </div>
  </div>
</template>


<script setup lang="ts">
import type { GanttEditorProps } from "../components/gantt-editor-lib/chart/gantt_canvas_props";
import { GanttChartCanvasController } from "../components/gantt-editor-lib/chart/gantt_chart_canvas_controller";
import type { ComponentPublicInstance } from "vue";
import { ref, watch, onMounted, onBeforeUnmount } from "vue";

interface GanttEditorEmits {
  onChangeStartAndEndTime: [Date, Date],
  onChangeDestinationId: [string, string, boolean],
  onBulkChangeDestinationId: [string[], string, boolean],
  onCopyToDestinationId: [string, string, boolean],
  onBulkCopyToDestinationId: [string[], string, boolean],
  onMoveSlotOnTimeAxis: [string, number, boolean],
  onBulkMoveSlotsOnTimeAxis: [string[], number, boolean],
  onCopySlotOnTimeAxis: [string, number, boolean],
  onBulkCopySlotsOnTimeAxis: [string[], number, boolean],
  onChangeSlotTime: [string, Date, Date],
  onSelectionChange: [string[]],
  onClickOnSlot: [string],
  onHoverOnSlot: [string],
  onDoubleClickOnSlot: [string],
  onContextClickOnSlot: [string],
  onTopContentPortionChange: [number, number],
  onChangeVerticalMarker: [string, Date],
  onClickVerticalMarker: [string],
  onContextMenuAction: [string, Date, string],
  onSlotContextMenuAction: [string, string],
}

type GanttEditorComponentProps = GanttEditorProps & {
  slotContextMenuActions?: GanttEditorProps["slotContextMenuActions"];
};

const props = defineProps<GanttEditorComponentProps>();
const emit = defineEmits<GanttEditorEmits>();

const chartContainerRef = ref<HTMLElement | null>(null);
const chartCanvasRef = ref<HTMLCanvasElement | null>(null);

const setChartContainerRef = (el: Element | ComponentPublicInstance | null) => {
  chartContainerRef.value = el instanceof HTMLElement ? el : null;
};

const setChartCanvasRef = (el: Element | ComponentPublicInstance | null) => {
  chartCanvasRef.value = el instanceof HTMLCanvasElement ? el : null;
};

const currentTopContentHeight = ref(0);
const exposeTestApi = import.meta.env.DEV || import.meta.env.MODE === "test";

type GanttCanvasTestApi = {
  flush: () => void;
  refreshSelectionFromStorage: () => void;
  getState: () => ReturnType<GanttChartCanvasController["getTestState"]>;
  probeCanvasPoint: (x: number, y: number) => ReturnType<GanttChartCanvasController["probeCanvasPoint"]>;
  findSlotPoint: (
    slotId: string,
    mode?: "center" | "left-edge" | "right-edge",
  ) => ReturnType<GanttChartCanvasController["findSlotPoint"]>;
};

let registeredTestApi: GanttCanvasTestApi | null = null;

const installTestApi = () => {
  if (!exposeTestApi) return;
  registeredTestApi = {
    flush: () => controller.flushForTests(),
    refreshSelectionFromStorage: () => controller.updateSelection(),
    getState: () => controller.getTestState(),
    probeCanvasPoint: (x, y) => controller.probeCanvasPoint(x, y),
    findSlotPoint: (slotId, mode = "center") => controller.findSlotPoint(slotId, mode),
  };
  (window as Window & { __ganttCanvasTestApi?: GanttCanvasTestApi }).__ganttCanvasTestApi = registeredTestApi;
};

const uninstallTestApi = () => {
  if (!exposeTestApi) return;
  const w = window as Window & { __ganttCanvasTestApi?: GanttCanvasTestApi };
  if (w.__ganttCanvasTestApi === registeredTestApi) {
    delete w.__ganttCanvasTestApi;
  }
  registeredTestApi = null;
};

function propsSnapshot(): GanttEditorProps {
  return {
    startTime: props.startTime,
    endTime: props.endTime,
    slots: props.slots,
    destinations: props.destinations,
    destinationGroups: props.destinationGroups,
    suggestions: props.suggestions,
    activateRulers: props.activateRulers,
    verticalMarkers: props.verticalMarkers,
    contextMenuActions: props.contextMenuActions,
    slotContextMenuActions: props.slotContextMenuActions,
    markedRegion: props.markedRegion,
    isReadOnly: props.isReadOnly,
    topContentPortion: props.topContentPortion,
    xAxisOptions: props.xAxisOptions,
    hoverPreviewMaxClipboardSize: props.hoverPreviewMaxClipboardSize,
    features: props.features,
    helpOverlayTiles: props.helpOverlayTiles,
    helpOverlayTileIds: props.helpOverlayTileIds,
  };
}

const controller = new GanttChartCanvasController(
  propsSnapshot(),
  {
    onChangeStartAndEndTime: (start, end) => {
      emit("onChangeStartAndEndTime", start, end);
    },
    onTopContentPortionChange: (portion, heightPx) => {
      emit("onTopContentPortionChange", portion, heightPx);
    },
    onChangeSlotTime: (slotId, openTime, closeTime) => {
      emit("onChangeSlotTime", slotId, openTime, closeTime);
    },
    onChangeDestinationId: (slotId, destinationId, preview) => {
      emit("onChangeDestinationId", slotId, destinationId, preview);
    },
    onBulkChangeDestinationId: (slotIds, destinationId, preview) => {
      emit("onBulkChangeDestinationId", slotIds, destinationId, preview);
    },
    onCopyToDestinationId: (slotId, destinationId, preview) => {
      emit("onCopyToDestinationId", slotId, destinationId, preview);
    },
    onBulkCopyToDestinationId: (slotIds, destinationId, preview) => {
      emit("onBulkCopyToDestinationId", slotIds, destinationId, preview);
    },
    onMoveSlotOnTimeAxis: (slotId, timeDiffMs, preview) => {
      emit("onMoveSlotOnTimeAxis", slotId, timeDiffMs, preview);
    },
    onBulkMoveSlotsOnTimeAxis: (slotIds, timeDiffMs, preview) => {
      emit("onBulkMoveSlotsOnTimeAxis", slotIds, timeDiffMs, preview);
    },
    onCopySlotOnTimeAxis: (slotId, timeDiffMs, preview) => {
      emit("onCopySlotOnTimeAxis", slotId, timeDiffMs, preview);
    },
    onBulkCopySlotsOnTimeAxis: (slotIds, timeDiffMs, preview) => {
      emit("onBulkCopySlotsOnTimeAxis", slotIds, timeDiffMs, preview);
    },
    onClickOnSlot: (slotId) => {
      emit("onClickOnSlot", slotId);
    },
    onHoverOnSlot: (slotId) => {
      emit("onHoverOnSlot", slotId);
    },
    onDoubleClickOnSlot: (slotId) => {
      emit("onDoubleClickOnSlot", slotId);
    },
    onContextClickOnSlot: (slotId) => {
      emit("onContextClickOnSlot", slotId);
    },
    onVerticalMarkerChange: (id, date) => {
      emit("onChangeVerticalMarker", id, date);
    },
    onVerticalMarkerClick: (id) => {
      emit("onClickVerticalMarker", id);
    },
    onContextMenuAction: (actionId, timestamp, destinationId) => {
      emit("onContextMenuAction", actionId, timestamp, destinationId);
    },
    onSlotContextMenuAction: (actionId, slotId) => {
      emit("onSlotContextMenuAction", actionId, slotId);
    },
  },
  {
    onSelectionSlotIds: (slotIds) => {
      emit("onSelectionChange", slotIds);
    },
    onTopContentHeightPx: (h) => {
      currentTopContentHeight.value = h;
    },
  },
);

let refreshQueued = false;
const queueRefreshModel = () => {
  if (refreshQueued) return;
  refreshQueued = true;
  queueMicrotask(() => {
    refreshQueued = false;
    controller.refreshModel(propsSnapshot());
  });
};

watch(
  () => [props.startTime.getTime(), props.endTime.getTime()],
  queueRefreshModel,
);
watch(
  () => [
    props.slots,
    props.destinations,
    props.destinationGroups,
    props.suggestions,
    props.activateRulers,
    props.verticalMarkers,
    props.contextMenuActions,
    props.slotContextMenuActions,
    props.isReadOnly,
    props.topContentPortion,
    props.xAxisOptions,
    props.features,
    props.helpOverlayTiles,
    props.helpOverlayTileIds,
  ],
  queueRefreshModel,
);
watch(
  () => props.markedRegion,
  queueRefreshModel,
  { deep: true },
);

onMounted(() => {
  controller.updateSelection();
  const root = chartContainerRef.value;
  const canvas = chartCanvasRef.value;
  if (root && canvas) {
    controller.attach(root, canvas);
  }
  installTestApi();
});

onBeforeUnmount(() => {
  uninstallTestApi();
  controller.detach();
});

const onContainerMouseMove = (e: MouseEvent) => {
  controller.onContainerMouseMove(e);
};
const onChartMouseMove = (e: MouseEvent) => {
  controller.onChartMouseMove(e);
};
const onChartMouseLeave = () => {
  controller.onChartMouseLeave();
};
const onCanvasMouseDown = (e: MouseEvent) => {
  controller.onCanvasMouseDown(e);
};
const onCanvasPointerUp = (e: PointerEvent) => {
  controller.onCanvasPointerUp(e);
};
const onCanvasClick = (e: MouseEvent) => {
  controller.onCanvasClick(e);
};
const onCanvasDoubleClick = (e: MouseEvent) => {
  controller.onCanvasDoubleClick(e);
};
const onMouseEnter = () => {
  controller.onMouseEnter();
};
const onMouseLeave = () => {
  controller.onMouseLeave();
};

const clearSelection = () => {
  controller.clearSelection();
};

const clearClipboard = () => {
  clearSelection();
};

defineExpose({
  clearSelection,
  clearClipboard,
  chartCanvas: chartCanvasRef,
  ganttCanvasTestApi: {
    flush: () => controller.flushForTests(),
    getState: () => controller.getTestState(),
    probeCanvasPoint: (x: number, y: number) => controller.probeCanvasPoint(x, y),
    findSlotPoint: (slotId: string, mode?: "center" | "left-edge" | "right-edge") =>
      controller.findSlotPoint(slotId, mode),
  },
});
</script>

<style lang="css">
.chart-container {
  color: #000;
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.chart-canvas-wrap {
  flex: 1;
  min-height: 0;
  width: 100%;
  position: relative;
}

.chart-canvas {
  display: block;
}

.top-content-container {
  width: 100%;
  overflow: hidden;
  background-color: white;
}
</style>

// src/angular/GanttEditor.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChild,
  Directive,
  ElementRef,
  EventEmitter,
  Input,
  NgZone,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import type { GanttEditorProps } from '../components/gantt-editor-lib/chart/gantt_canvas_props'
import { GanttChartCanvasController } from '../components/gantt-editor-lib/chart/gantt_chart_canvas_controller'

type SlotPointMode = 'center' | 'left-edge' | 'right-edge'

type GanttCanvasTestApi = {
  flush: () => void
  refreshSelectionFromStorage: () => void
  getState: () => ReturnType<GanttChartCanvasController['getTestState']>
  probeCanvasPoint: (x: number, y: number) => ReturnType<GanttChartCanvasController['probeCanvasPoint']>
  findSlotPoint: (slotId: string, mode?: SlotPointMode) => ReturnType<GanttChartCanvasController['findSlotPoint']>
}

@Directive({
  selector: '[ganttEditorTopContent]',
})
export class GanttEditorTopContentDirective {}

@Component({
  selector: 'gantt-editor',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [
    `
      .chart-container {
        color: #000;
        position: relative;
        width: 100%;
        height: 100%;
        overflow: hidden;
        display: flex;
        flex-direction: column;
      }

      .top-content-container {
        width: 100%;
        overflow: hidden;
        background-color: white;
      }

      .chart-canvas-wrap {
        flex: 1;
        min-height: 0;
        width: 100%;
        position: relative;
      }

      .chart-canvas {
        display: block;
      }
    `,
  ],
  template: `
    <div
      #chartContainer
      class="chart-container"
      (mousemove)="onContainerMouseMove($event)"
      (mouseenter)="onMouseEnter()"
      (mouseleave)="onMouseLeave()"
    >
      <div
        *ngIf="hasTopContent()"
        class="top-content-container"
        [style.height.px]="currentTopContentHeight"
      >
        <ng-content select="[ganttEditorTopContent]"></ng-content>
      </div>

      <div class="chart-canvas-wrap">
        <canvas
          #chartCanvas
          class="chart-canvas"
          (mousedown)="onCanvasMouseDown($event)"
          (pointerup)="onCanvasPointerUp($event)"
          (click)="onCanvasClick($event)"
          (dblclick)="onCanvasDoubleClick($event)"
          (contextmenu)="$event.preventDefault()"
          (mousemove)="onChartMouseMove($event)"
          (mouseleave)="onChartMouseLeave()"
        ></canvas>
      </div>
    </div>
  `,
})
export class GanttEditor implements GanttEditorProps, AfterViewInit, OnChanges, OnDestroy {
  @Input({ required: true }) startTime!: Date
  @Input({ required: true }) endTime!: Date
  @Input({ required: true }) slots!: GanttEditorProps['slots']
  @Input({ required: true }) destinations!: GanttEditorProps['destinations']
  @Input({ required: true }) destinationGroups!: GanttEditorProps['destinationGroups']
  @Input({ required: true }) suggestions!: GanttEditorProps['suggestions']
  @Input() activateRulers?: GanttEditorProps['activateRulers']
  @Input() verticalMarkers?: GanttEditorProps['verticalMarkers']
  @Input() contextMenuActions?: GanttEditorProps['contextMenuActions']
  @Input() slotContextMenuActions?: GanttEditorProps['slotContextMenuActions']
  @Input({ required: true }) markedRegion!: GanttEditorProps['markedRegion']
  @Input({ required: true }) isReadOnly!: boolean
  @Input() topContentPortion?: number
  @Input() xAxisOptions?: GanttEditorProps['xAxisOptions']
  @Input() hoverPreviewMaxClipboardSize?: number
  @Input() features?: GanttEditorProps['features']
  @Input() helpOverlayTiles?: GanttEditorProps['helpOverlayTiles']
  @Input() helpOverlayTileIds?: GanttEditorProps['helpOverlayTileIds']

  @Output() onChangeStartAndEndTime = new EventEmitter<[Date, Date]>()
  @Output() onChangeDestinationId = new EventEmitter<[string, string, boolean]>()
  @Output() onBulkChangeDestinationId = new EventEmitter<[string[], string, boolean]>()
  @Output() onCopyToDestinationId = new EventEmitter<[string, string, boolean]>()
  @Output() onBulkCopyToDestinationId = new EventEmitter<[string[], string, boolean]>()
  @Output() onMoveSlotOnTimeAxis = new EventEmitter<[string, number, boolean]>()
  @Output() onBulkMoveSlotsOnTimeAxis = new EventEmitter<[string[], number, boolean]>()
  @Output() onCopySlotOnTimeAxis = new EventEmitter<[string, number, boolean]>()
  @Output() onBulkCopySlotsOnTimeAxis = new EventEmitter<[string[], number, boolean]>()
  @Output() onChangeSlotTime = new EventEmitter<[string, Date, Date]>()
  @Output() onSelectionChange = new EventEmitter<string[]>()
  @Output() onClickOnSlot = new EventEmitter<string>()
  @Output() onHoverOnSlot = new EventEmitter<string>()
  @Output() onDoubleClickOnSlot = new EventEmitter<string>()
  @Output() onContextClickOnSlot = new EventEmitter<string>()
  @Output() onTopContentPortionChange = new EventEmitter<[number, number]>()
  @Output() onChangeVerticalMarker = new EventEmitter<[string, Date]>()
  @Output() onClickVerticalMarker = new EventEmitter<string>()
  @Output() onContextMenuAction = new EventEmitter<[string, Date, string]>()
  @Output() onSlotContextMenuAction = new EventEmitter<[string, string]>()

  @ViewChild('chartContainer', { static: true })
  private chartContainerRef!: ElementRef<HTMLElement>

  @ViewChild('chartCanvas', { static: true })
  private chartCanvasRef!: ElementRef<HTMLCanvasElement>

  @ContentChild(GanttEditorTopContentDirective)
  private topContentDirective: GanttEditorTopContentDirective | null = null

  currentTopContentHeight = 0
  readonly ganttCanvasTestApi: GanttCanvasTestApi = {
    flush: () => this.controller.flushForTests(),
    refreshSelectionFromStorage: () => this.controller.updateSelection(),
    getState: () => this.controller.getTestState(),
    probeCanvasPoint: (x: number, y: number) => this.controller.probeCanvasPoint(x, y),
    findSlotPoint: (slotId: string, mode: SlotPointMode = 'center') =>
      this.controller.findSlotPoint(slotId, mode),
  }

  private static readonly INITIAL_CONTROLLER_PROPS: GanttEditorProps = {
    startTime: new Date(0),
    endTime: new Date(1),
    slots: [],
    destinations: [],
    destinationGroups: [],
    suggestions: [],
    markedRegion: null,
    isReadOnly: true,
  }

  private readonly controller = new GanttChartCanvasController(
    GanttEditor.INITIAL_CONTROLLER_PROPS,
    {
      onChangeStartAndEndTime: (start, end) => this.onChangeStartAndEndTime.emit([start, end]),
      onTopContentPortionChange: (portion, heightPx) =>
        this.onTopContentPortionChange.emit([portion, heightPx]),
      onChangeSlotTime: (slotId, openTime, closeTime) =>
        this.onChangeSlotTime.emit([slotId, openTime, closeTime]),
      onChangeDestinationId: (slotId, destinationId, preview) =>
        this.onChangeDestinationId.emit([slotId, destinationId, preview]),
      onBulkChangeDestinationId: (slotIds, destinationId, preview) =>
        this.onBulkChangeDestinationId.emit([slotIds, destinationId, preview]),
      onCopyToDestinationId: (slotId, destinationId, preview) =>
        this.onCopyToDestinationId.emit([slotId, destinationId, preview]),
      onBulkCopyToDestinationId: (slotIds, destinationId, preview) =>
        this.onBulkCopyToDestinationId.emit([slotIds, destinationId, preview]),
      onMoveSlotOnTimeAxis: (slotId, timeDiffMs, preview) =>
        this.onMoveSlotOnTimeAxis.emit([slotId, timeDiffMs, preview]),
      onBulkMoveSlotsOnTimeAxis: (slotIds, timeDiffMs, preview) =>
        this.onBulkMoveSlotsOnTimeAxis.emit([slotIds, timeDiffMs, preview]),
      onCopySlotOnTimeAxis: (slotId, timeDiffMs, preview) =>
        this.onCopySlotOnTimeAxis.emit([slotId, timeDiffMs, preview]),
      onBulkCopySlotsOnTimeAxis: (slotIds, timeDiffMs, preview) =>
        this.onBulkCopySlotsOnTimeAxis.emit([slotIds, timeDiffMs, preview]),
      onClickOnSlot: (slotId) => this.onClickOnSlot.emit(slotId),
      onHoverOnSlot: (slotId) => this.onHoverOnSlot.emit(slotId),
      onDoubleClickOnSlot: (slotId) => this.onDoubleClickOnSlot.emit(slotId),
      onContextClickOnSlot: (slotId) => this.onContextClickOnSlot.emit(slotId),
      onVerticalMarkerChange: (id, date) => this.onChangeVerticalMarker.emit([id, date]),
      onVerticalMarkerClick: (id) => this.onClickVerticalMarker.emit(id),
      onContextMenuAction: (actionId, timestamp, destinationId) =>
        this.onContextMenuAction.emit([actionId, timestamp, destinationId]),
      onSlotContextMenuAction: (actionId, slotId) =>
        this.onSlotContextMenuAction.emit([actionId, slotId]),
    },
    {
      onSelectionSlotIds: (slotIds) => this.onSelectionChange.emit(slotIds),
      onTopContentHeightPx: (heightPx) => {
        this.currentTopContentHeight = heightPx
        this.cdr.markForCheck()
      },
    },
  )

  private refreshQueued = false
  private isAttached = false
  private readonly exposeTestApi = typeof window !== 'undefined'
  private registeredTestApi: GanttCanvasTestApi | null = null

  constructor(
    private readonly cdr: ChangeDetectorRef,
    private readonly ngZone: NgZone,
  ) {}

  ngAfterViewInit(): void {
    // Inputs are assigned after construction; sync the model before first render.
    this.controller.refreshModel(this.propsSnapshot())
    this.controller.updateSelection()
    this.controller.attach(this.chartContainerRef.nativeElement, this.chartCanvasRef.nativeElement)
    this.installTestApi()
    this.isAttached = true
  }

  ngOnChanges(_changes: SimpleChanges): void {
    if (!this.isAttached) return
    this.queueRefreshModel()
  }

  ngOnDestroy(): void {
    this.uninstallTestApi()
    this.controller.detach()
    this.isAttached = false
  }

  get chartCanvas(): HTMLCanvasElement | null {
    return this.chartCanvasRef?.nativeElement ?? null
  }

  hasTopContent(): boolean {
    return Boolean(this.topContentDirective) || Boolean(this.topContentPortion)
  }

  clearSelection(): void {
    this.controller.clearSelection()
  }

  clearClipboard(): void {
    this.controller.clearSelection()
  }

  onContainerMouseMove(event: MouseEvent): void {
    this.controller.onContainerMouseMove(event)
  }

  onChartMouseMove(event: MouseEvent): void {
    this.controller.onChartMouseMove(event)
  }

  onChartMouseLeave(): void {
    this.controller.onChartMouseLeave()
  }

  onCanvasMouseDown(event: MouseEvent): void {
    this.controller.onCanvasMouseDown(event)
  }

  onCanvasPointerUp(event: PointerEvent): void {
    this.controller.onCanvasPointerUp(event)
  }

  onCanvasClick(event: MouseEvent): void {
    this.controller.onCanvasClick(event)
  }

  onCanvasDoubleClick(event: MouseEvent): void {
    this.controller.onCanvasDoubleClick(event)
  }

  onMouseEnter(): void {
    this.controller.onMouseEnter()
  }

  onMouseLeave(): void {
    this.controller.onMouseLeave()
  }

  private queueRefreshModel(): void {
    if (this.refreshQueued) return
    this.refreshQueued = true
    this.ngZone.runOutsideAngular(() => {
      queueMicrotask(() => {
        this.refreshQueued = false
        this.controller.refreshModel(this.propsSnapshot())
      })
    })
  }

  private installTestApi(): void {
    if (!this.exposeTestApi || typeof window === 'undefined') return
    this.registeredTestApi = this.ganttCanvasTestApi
    ;(window as Window & { __ganttCanvasTestApi?: GanttCanvasTestApi }).__ganttCanvasTestApi =
      this.registeredTestApi
  }

  private uninstallTestApi(): void {
    if (!this.exposeTestApi || typeof window === 'undefined') return
    const w = window as Window & { __ganttCanvasTestApi?: GanttCanvasTestApi }
    if (w.__ganttCanvasTestApi === this.registeredTestApi) {
      delete w.__ganttCanvasTestApi
    }
    this.registeredTestApi = null
  }

  private propsSnapshot(): GanttEditorProps {
    return {
      startTime: this.startTime,
      endTime: this.endTime,
      slots: this.slots,
      destinations: this.destinations,
      destinationGroups: this.destinationGroups,
      suggestions: this.suggestions,
      activateRulers: this.activateRulers,
      verticalMarkers: this.verticalMarkers,
      contextMenuActions: this.contextMenuActions,
      slotContextMenuActions: this.slotContextMenuActions,
      markedRegion: this.markedRegion,
      isReadOnly: this.isReadOnly,
      topContentPortion: this.topContentPortion,
      xAxisOptions: this.xAxisOptions,
      hoverPreviewMaxClipboardSize: this.hoverPreviewMaxClipboardSize,
      features: this.features,
      helpOverlayTiles: this.helpOverlayTiles,
      helpOverlayTileIds: this.helpOverlayTileIds,
    }
  }
}
